CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -59,8 +59,9 @@ jobs:
       with:
         group: org.ow2.asm
         name: asm
-        min: 6.0, 6.1.999
+        min: 5, 6.0
         max: 7.0.999
+        exclude: 7.1
 
     - name: Validate current action
       env:
@@ -72,16 +73,16 @@ jobs:
           echo "::error Current action output doesn't contain '6.1.1': $OUTPUT"
           exit 1
         fi
-        if [ "${{ contains(fromJSON(env.OUTPUT), '7.1') }}" == "false" ]; then
-          echo "Valid"
-        else
-          echo "::error Current action output contains '7.1': $OUTPUT"
+        if [ "${{ contains(fromJSON(env.OUTPUT), '5.1') }}" != "false" ]; then
+          echo "::error Current action output contains '5.1': $OUTPUT"
           exit 1
         fi
-        if [ "${{ contains(fromJSON(env.OUTPUT), '6.0') }}" == "false" ]; then
-          echo "Valid"
-        else
-          echo "::error Current action output contains '6.0': $OUTPUT"
+        if [ "${{ contains(fromJSON(env.OUTPUT), '8.0') }}" != "false" ]; then
+          echo "::error Current action output contains '5.1': $OUTPUT"
+          exit 1
+        fi
+        if [ "${{ contains(fromJSON(env.OUTPUT), '7.1') }}" != "false" ]; then
+          echo "::error Current action output contains '7.1': $OUTPUT"
           exit 1
         fi
 
